//
//  DrinkDetailInteractor.swift
//  MakeCocktails
//
//  Created by Andrey Nedov on 04/05/2019.
//  Copyright (c) 2019 Andrey Nedov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DrinkDetailBusinessLogic
{
    func fetchDrinkDetail(request: DrinkDetail.FetchDrink.Request)
}

protocol DrinkDetailDataStore
{
    var drinkID: String? { get set }
}

class DrinkDetailInteractor: DrinkDetailBusinessLogic, DrinkDetailDataStore
{
    // MARK: Properties
    
    var presenter: DrinkDetailPresentationLogic?
    var apiWorker: DrinkDetailWorker = DrinkDetailWorker(service: APIService())

    // MARK: DrinkDetailDataStore
    
    var drinkID: String?
    
    // MARK: Do DrinkDetailBusinessLogic
    
    func fetchDrinkDetail(request: DrinkDetail.FetchDrink.Request) {
        guard let drinkID = drinkID else { return }
        apiWorker.getDrinkDetail(by: drinkID) { (result) in
            let response = DrinkDetail.FetchDrink.Response(result: result)
            self.presenter?.presentDrinkDetail(response: response)
        }
    }

}

