//
//  DrinkDetailInteractor.swift
//  MakeCocktails
//
//  Created by Andrey Nedov on 04/05/2019.
//  Copyright (c) 2019 Andrey Nedov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DrinkDetailBusinessLogic
{
    func fetchAlbumDetail(request: DrinkDetail.FetchDrink.Request)
}

protocol DrinkDetailDataStore
{
    var drinkID: String? { get set }
}

class DrinkDetailInteractor: DrinkDetailBusinessLogic, DrinkDetailDataStore
{
    var presenter: DrinkDetailPresentationLogic?
    var apiWorker: DrinkDetailWorker = DrinkDetailWorker(service: APIService())
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: DrinkDetail.Something.Request)
    {
        worker = DrinkDetailWorker()
        worker?.doSomeWork()
        
        let response = DrinkDetail.Something.Response()
        presenter?.presentSomething(response: response)
    }
}

