//
//  DrinkDetailPresenter.swift
//  MakeCocktails
//
//  Created by Andrey Nedov on 04/05/2019.
//  Copyright (c) 2019 Andrey Nedov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DrinkDetailPresentationLogic
{
  func presentSomething(response: DrinkDetail.Something.Response)
}

class DrinkDetailPresenter: DrinkDetailPresentationLogic
{
  weak var viewController: DrinkDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: DrinkDetail.Something.Response)
  {
    let viewModel = DrinkDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
