//
//  DrinksListPresenter.swift
//  MakeCocktails
//
//  Created by Andrey Nedov on 22/03/2019.
//  Copyright (c) 2019 Andrey Nedov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DrinksListPresentationLogic
{
    func presentDrinks(response: DrinksList.FetchDrinks.Response)
}

class DrinksListPresenter: DrinksListPresentationLogic
{
    weak var viewController: DrinksListDisplayLogic?
    
    // MARK: DrinksListPresentationLogic
    
    func presentDrinks(response: DrinksList.FetchDrinks.Response)
    {
        switch response.result {
        case .success(let drinks):
            handleSuccessFetchedDrinks(drinks)
        case .failure(let error):
            handleError(error)
        }
    }
    
    // MARK: Private Helpers
    
    private func handleSuccessFetchedDrinks(_ drinks: [Drink]?) {
        guard let artists = artists else { return }
        var displayedArtists: [DisplayedArtist] = []
        for artist in artists {
            let displayedArtist = DisplayedArtist(with: artist)
            displayedArtists.append(displayedArtist)
        }
        let viewModel = SearchScreen.FetchArtists.ViewModel.Success(displayedArtists: displayedArtists)
        viewController?.displayArtists(viewModel: viewModel)
    }
    
    private func handleError(_ error: Error) {
        let errorViewModel = ErrorViewModel(error: error)
        let viewModel = DrinksList.FetchDrinks.ViewModel.Failure(errorViewModel: errorViewModel)
        viewController?.displayError(viewModel: viewModel)
    }
}

