//
//  DrinksListWorker.swift
//  MakeCocktails
//
//  Created by Andrey Nedov on 22/03/2019.
//  Copyright (c) 2019 Andrey Nedov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DrinksListWorker
{
    // MARK: Properties
    
    var service: ServicesProtocol
    
    // MARK: Initialization
    
    init(service: ServicesProtocol) {
        self.service = service
    }
    
    // MARK: MainScreenBusinessLogic
    
    func getPopularDrinks(completion: @escaping (Result<[DrinkModel]?>) -> Void) {
        service.getPopularDrinks { (result) in
            DispatchQueue.main.async {
                completion(result)
            }
        }
    }
    
    func getDrinksByName(_ text: String, completion: @escaping (Result<[DrinkModel]?>) -> Void) {
        service.getDrinksByName(text) { (result) in
            DispatchQueue.main.async {
                completion(result)
            }
        }
    }
    
    func getDrinksByIngredients(_ text: String, completion: @escaping (Result<[DrinkModel]?>) -> Void) {
        service.getDrinksByIngredients(text) { (result) in
            DispatchQueue.main.async {
                completion(result)
            }
        }
    }
}
