//
//  DrinksListPresenter.swift
//  MakeCocktails
//
//  Created by Andrey Nedov on 22/03/2019.
//  Copyright (c) 2019 Andrey Nedov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DrinksListPresentationLogic
{
    func presentDrinks(response: DrinksList.FetchDrinks.Response)
}

class DrinksListPresenter: DrinksListPresentationLogic
{
    weak var viewController: DrinksListDisplayLogic?
    
    // MARK: DrinksListPresentationLogic
    
    func presentDrinks(response: DrinksList.FetchDrinks.Response)
    {
        switch response.result {
        case .success(let drinks):
            handleSuccessFetchedDrinks(drinks)
        case .failure(let error):
            handleError(error)
        }
    }
    
    // MARK: Private Helpers
    
    private func handleSuccessFetchedDrinks(_ drinks: [Drink]?) {
        guard let drinks = drinks else { return }
        var displayedDrinks: [DisplayedDrink] = []
        for drink in drinks {
            let displayedDrink = DisplayedDrink(with: drink)
            displayedDrinks.append(displayedDrink)
        }
        let viewModel = DrinksList.FetchDrinks.ViewModel.Success(displayedDrinks: displayedDrinks)
        viewController?.displayDrinks(viewModel: viewModel)
    }
    
    private func handleError(_ error: Error) {
        let errorViewModel = ErrorViewModel(error: error)
        let viewModel = DrinksList.FetchDrinks.ViewModel.Failure(errorViewModel: errorViewModel)
        viewController?.displayError(viewModel: viewModel)
    }
}

