//
//  DrinksListModels.swift
//  MakeCocktails
//
//  Created by Andrey Nedov on 22/03/2019.
//  Copyright (c) 2019 Andrey Nedov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias DisplayedDrink = DrinksList.FetchDrinks.ViewModel.Success.DisplayedDrink

enum DrinksList
{
    // MARK: Use cases
    
    enum FetchDrinks
    {
        static let `default` = ""

        struct Request{
            var searchText: String
        }
        
        struct Response{
            let result: Result<[DrinkModel]?>
        }
        
        struct ViewModel{
            struct Success {
                struct DisplayedDrink {
                    let drinkName: String
                    let drinkID: String
                    let imageURL: String
                    let category: String
                    init(with drinkModel: DrinkModel) {
                        drinkName = drinkModel.name ?? ""
                        drinkID = drinkModel.id ?? ""
                        imageURL = drinkModel.imageURL ?? ""
                        category = drinkModel.category ?? ""
                    }
                }
                let displayedDrinks: [DisplayedDrink]
            }
            struct Failure {
                let errorViewModel: ErrorViewModel
            }
        }
        
        
    }
    enum SelectDrink {
        struct Request {
            let drinkID: String
        }
        struct Response {}
        struct ViewModel {}
    }
}


